import { Command } from "commander";
import {
  existsSync,
  readFileSync,
  writeFileSync,
  mkdirSync,
} from "node:fs";
import { join } from "node:path";
import { readdirSync } from "node:fs";
import { readConfig, getConfigDir } from "../utils/config.js";
import { success, warn, info } from "../utils/ui.js";
import { createClient } from "../utils/api.js";
import { getRepoFullName } from "../utils/git.js";

interface GeneratorResult {
  filePath: string;
  content: string;
}

function readPromptTemplates(): Record<string, string> {
  const promptsDir = join(getConfigDir(), "prompts");
  const templates: Record<string, string> = {};

  if (!existsSync(promptsDir)) return templates;

  for (const file of readdirSync(promptsDir)) {
    if (!file.endsWith(".md")) continue;
    const name = file.replace(/\.md$/, "");
    templates[name] = readFileSync(join(promptsDir, file), "utf-8");
  }
  return templates;
}

function readOverrides(): Record<string, string> {
  const overridesDir = join(getConfigDir(), "overrides");
  const overrides: Record<string, string> = {};

  if (!existsSync(overridesDir)) return overrides;

  for (const file of readdirSync(overridesDir)) {
    if (!file.endsWith(".md")) continue;
    const name = file.replace(/\.md$/, "");
    overrides[name] = readFileSync(join(overridesDir, file), "utf-8");
  }
  return overrides;
}

function mergeTemplates(
  base: Record<string, string>,
  overrides: Record<string, string>,
): Record<string, string> {
  return { ...base, ...overrides };
}

function generateClaudeMd(templates: Record<string, string>): GeneratorResult {
  const sections = Object.entries(templates)
    .map(([name, content]) => `## ${name}\n\n${content.trim()}`)
    .join("\n\n---\n\n");

  return {
    filePath: "CLAUDE.md",
    content: `# AIRails Prompt Templates\n\n> Auto-generated by \`airails sync\`. Edit templates in \`.airails/prompts/\`.\n\n${sections}\n`,
  };
}

function generateCursorRules(
  templates: Record<string, string>,
): GeneratorResult {
  const sections = Object.entries(templates)
    .map(([name, content]) => `# ${name}\n\n${content.trim()}`)
    .join("\n\n");

  return {
    filePath: ".cursorrules",
    content: `# AIRails Prompt Templates\n# Auto-generated by \`airails sync\`. Edit templates in \`.airails/prompts/\`.\n\n${sections}\n`,
  };
}

function generateCopilotInstructions(
  templates: Record<string, string>,
): GeneratorResult {
  const sections = Object.entries(templates)
    .map(([name, content]) => `## ${name}\n\n${content.trim()}`)
    .join("\n\n---\n\n");

  return {
    filePath: join(".github", "copilot-instructions.md"),
    content: `# AIRails Prompt Templates\n\n> Auto-generated by \`airails sync\`. Edit templates in \`.airails/prompts/\`.\n\n${sections}\n`,
  };
}

function generateContinueConfig(
  templates: Record<string, string>,
): GeneratorResult {
  const instructions = Object.entries(templates)
    .map(([name, content]) => `[${name}]\n${content.trim()}`)
    .join("\n\n");

  const config = {
    systemMessage: instructions,
    _comment:
      "Auto-generated by `airails sync`. Edit templates in `.airails/prompts/`.",
  };

  return {
    filePath: ".continuerc.json",
    content: JSON.stringify(config, null, 2) + "\n",
  };
}

const GENERATORS: Record<
  string,
  (templates: Record<string, string>) => GeneratorResult
> = {
  claude: generateClaudeMd,
  cursor: generateCursorRules,
  copilot: generateCopilotInstructions,
  continue: generateContinueConfig,
};

function backupIfModified(filePath: string, expectedContent: string): boolean {
  if (!existsSync(filePath)) return false;

  const current = readFileSync(filePath, "utf-8");
  if (current === expectedContent) return false;

  // File was manually edited — back it up
  const timestamp = new Date().toISOString().replace(/[:.]/g, "-");
  const backupDir = join(getConfigDir(), ".backups", timestamp);
  mkdirSync(backupDir, { recursive: true });

  const parts = filePath.split("/");
  const fileName = parts[parts.length - 1] ?? filePath;
  writeFileSync(join(backupDir, fileName), current);
  return true;
}

export const syncCommand = new Command("sync")
  .description(
    "Generate native AI tool configs from .airails/ templates",
  )
  .option("--quiet", "Suppress output (for hooks)")
  .action(async (options: { quiet?: boolean }) => {
    const config = readConfig();
    const tools = config.sync?.tools ?? ["claude", "cursor", "copilot"];

    const base = readPromptTemplates();
    const overrides = readOverrides();
    const templates = mergeTemplates(base, overrides);

    if (Object.keys(templates).length === 0) {
      if (!options.quiet) {
        warn("No prompt templates found in .airails/prompts/");
      }
      return;
    }

    const toolsGenerated: string[] = [];

    for (const tool of tools) {
      const generator = GENERATORS[tool];
      if (!generator) {
        if (!options.quiet) warn(`Unknown tool: ${tool}`);
        continue;
      }

      const result = generator(templates);

      // Ensure parent directory exists
      const parentDir = result.filePath.includes("/")
        ? result.filePath.split("/").slice(0, -1).join("/")
        : null;
      if (parentDir) mkdirSync(parentDir, { recursive: true });

      const wasModified = backupIfModified(result.filePath, result.content);
      if (wasModified && !options.quiet) {
        warn(
          `${result.filePath} was modified outside of .airails/`,
        );
        info(
          `  Backed up to .airails/.backups/`,
        );
        info("  Regenerated from .airails/ source of truth.");
      }

      writeFileSync(result.filePath, result.content);
      toolsGenerated.push(tool);

      if (!options.quiet) {
        success(`Generated ${result.filePath}`);
      }
    }

    // Report sync event to gateway
    if (toolsGenerated.length > 0) {
      try {
        const client = createClient();
        const repoFullName = getRepoFullName();
        if (repoFullName) {
          // Compute a simple config hash
          const contentHash = Buffer.from(
            JSON.stringify(templates),
          ).toString("base64url").slice(0, 16);

          await client.post("/api/sync/trigger", {
            repoFullName,
            toolsGenerated,
            configHash: contentHash,
          });
        }
      } catch {
        // Sync reporting is best-effort — don't fail the command
      }
    }

    if (!options.quiet) {
      const count = toolsGenerated.length;
      success(`Synced ${count} tool config${count === 1 ? "" : "s"}`);
    }
  });
