import { prisma } from "@airails/shared";
import type { HeuristicsCommitData } from "../types.js";

export interface SignalResult {
  signal: string;
  confidence: number;
  details: string;
}

const RAPID_SUCCESSION_THRESHOLD = 5;
const RAPID_SUCCESSION_WINDOW_MIN = 60;
const LARGE_COMMIT_MULTIPLIER = 3;

// ── Signal 1: rapid_succession (0.30) ──────────────────────────────────────

export async function detectRapidSuccession(
  engineerId: string,
  productId: string,
  commitTimestamp: Date,
): Promise<SignalResult | null> {
  const windowStart = new Date(
    commitTimestamp.getTime() - RAPID_SUCCESSION_WINDOW_MIN * 60 * 1000,
  );

  const recentCount = await prisma.aiActivity.count({
    where: {
      productId,
      engineerId,
      captureMethod: "COMMIT_TAG",
      createdAt: { gte: windowStart, lte: commitTimestamp },
    },
  });

  if (recentCount >= RAPID_SUCCESSION_THRESHOLD) {
    return {
      signal: "rapid_succession",
      confidence: 0.3,
      details: `${recentCount} commits in last 60 minutes`,
    };
  }
  return null;
}

// ── Signal 2: large_commit (0.25) ──────────────────────────────────────────

export async function detectLargeCommit(
  engineerId: string,
  productId: string,
  commit: HeuristicsCommitData,
): Promise<SignalResult | null> {
  const filesChanged =
    commit.added.length + commit.removed.length + commit.modified.length;

  // Get engineer's average commit size in this product
  const avgSize = await getAverageCommitSize(engineerId, productId);
  if (avgSize === 0) return null;

  if (filesChanged > avgSize * LARGE_COMMIT_MULTIPLIER) {
    return {
      signal: "large_commit",
      confidence: 0.25,
      details: `${filesChanged} files changed vs avg ${Math.round(avgSize)}`,
    };
  }
  return null;
}

async function getAverageCommitSize(
  engineerId: string,
  productId: string,
): Promise<number> {
  const activities = await prisma.aiActivity.findMany({
    where: {
      productId,
      engineerId,
      commitSha: { not: null },
    },
    select: { metadata: true },
    take: 50,
    orderBy: { createdAt: "desc" },
  });

  if (activities.length === 0) return 0;

  const sizes = activities
    .map((a) => {
      const meta = a.metadata as Record<string, unknown> | null;
      return typeof meta?.filesChanged === "number" ? meta.filesChanged : null;
    })
    .filter((s): s is number => s !== null);

  if (sizes.length === 0) return 0;
  return sizes.reduce((sum, s) => sum + s, 0) / sizes.length;
}

// ── Signal 3: ai_markers (0.40) ────────────────────────────────────────────

const AI_MARKER_PATTERNS: { pattern: RegExp; label: string }[] = [
  { pattern: /\/\/ TODO: implement/i, label: "todo-placeholder" },
  { pattern: /\/\/ Generated by/i, label: "generated-comment" },
  { pattern: /Here's (a|the|an) /i, label: "conversational-comment" },
  { pattern: /# Generated by/i, label: "generated-comment-hash" },
  { pattern: /\/\/ This (function|method|class) /i, label: "explanatory-comment" },
  { pattern: /as requested/i, label: "conversational-marker" },
];

export function detectAiMarkers(commitMessage: string): SignalResult | null {
  const markers: string[] = [];
  for (const { pattern, label } of AI_MARKER_PATTERNS) {
    if (pattern.test(commitMessage)) {
      markers.push(label);
    }
  }
  if (markers.length > 0) {
    return {
      signal: "ai_markers",
      confidence: 0.4,
      details: `Markers: ${markers.join(", ")}`,
    };
  }
  return null;
}

// ── Signal 4: unusual_timing (0.15) ────────────────────────────────────────

export async function detectUnusualTiming(
  engineerId: string,
  productId: string,
  commitTimestamp: Date,
): Promise<SignalResult | null> {
  const usualHours = await getUsualCommitHours(engineerId, productId);
  if (usualHours.length === 0) return null;

  const commitHour = commitTimestamp.getUTCHours();
  if (!usualHours.includes(commitHour)) {
    return {
      signal: "unusual_timing",
      confidence: 0.15,
      details: `Commit at ${commitHour}:00 UTC, usual hours: ${usualHours.join(", ")}`,
    };
  }
  return null;
}

async function getUsualCommitHours(
  engineerId: string,
  productId: string,
): Promise<number[]> {
  const activities = await prisma.aiActivity.findMany({
    where: { productId, engineerId, commitSha: { not: null } },
    select: { createdAt: true },
    take: 100,
    orderBy: { createdAt: "desc" },
  });

  if (activities.length < 10) return [];

  const hourCounts = new Map<number, number>();
  for (const a of activities) {
    const h = a.createdAt.getUTCHours();
    hourCounts.set(h, (hourCounts.get(h) ?? 0) + 1);
  }

  // Usual hours = hours with >= 10% of total commits
  const threshold = activities.length * 0.1;
  return [...hourCounts.entries()]
    .filter(([, count]) => count >= threshold)
    .map(([hour]) => hour)
    .sort((a, b) => a - b);
}

// ── Signal 5: style_deviation (0.35) ───────────────────────────────────────

export function detectStyleDeviation(
  commitMessage: string,
): SignalResult | null {
  const deviations: string[] = [];

  // Check for overly verbose commit messages typical of AI
  if (commitMessage.length > 200) {
    deviations.push("verbose-message");
  }

  // Check for list-style commit messages
  if (/^\s*[-*]\s/m.test(commitMessage) && commitMessage.split("\n").length > 5) {
    deviations.push("list-style-message");
  }

  // Check for very formal/structured messages
  if (/^(feat|fix|refactor|chore|docs|test|style|perf|ci|build)\(.+\):/i.test(commitMessage) === false &&
      /^(Add|Update|Fix|Remove|Refactor|Implement|Create) /i.test(commitMessage) &&
      commitMessage.includes(".") &&
      commitMessage.length > 100) {
    deviations.push("structured-description");
  }

  if (deviations.length > 0) {
    return {
      signal: "style_deviation",
      confidence: 0.35,
      details: `Deviations: ${deviations.join(", ")}`,
    };
  }
  return null;
}
